In [1]:
import numpy as np
from tensorflow.keras.models import load_model
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd
import os

In [2]:
# model = load_model('best_model_4.h5')
# input_shape = (100,100)


2023-05-05 09:47:08.794002: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# https://stackoverflow.com/questions/34588464/python-how-to-capture-image-from-webcam-on-click-using-opencv
# import cv2

# cam = cv2.VideoCapture(0)

# cv2.namedWindow("test")

# img_counter = 0

# while True:
#     ret, frame = cam.read()
#     if not ret:
#         print("failed to grab frame")
#         break
#     cv2.imshow("test", frame)

#     k = cv2.waitKey(1)
#     if k%256 == 27:
#         # ESC pressed
#         print("Escape hit, closing...")
#         break
#     elif k%256 == 32:
#         # SPACE pressed
#         img_name = "opencv_frame_{}.png".format(img_counter)
#         cv2.imwrite(img_name, frame)
#         print("{} written!".format(img_name))
#         img_counter += 1

# cam.release()

# cv2.destroyAllWindows()

opencv_frame_0.png written!
opencv_frame_1.png written!
opencv_frame_2.png written!
opencv_frame_3.png written!
opencv_frame_4.png written!
opencv_frame_5.png written!
opencv_frame_6.png written!
opencv_frame_7.png written!
opencv_frame_8.png written!
opencv_frame_9.png written!
opencv_frame_10.png written!
opencv_frame_11.png written!
opencv_frame_12.png written!
opencv_frame_13.png written!
Escape hit, closing...


In [3]:
# # https://medium.com/@jinilcs/a-simple-keras-model-on-my-laptop-webcam-dda77521e6a0
# import cv2
# import numpy as np
# from PIL import Image
# from keras import models
# import pandas as pd

# #Load the saved model
# video = cv2.VideoCapture(0)
# input_shape = (100,100)

# while True:
#     _, frame = video.read()

#     # frame = cv2.imread(filename)
#     #Convert the captured frame into RGB
#     im = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
#     face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
#     faces = face_cascade.detectMultiScale(frame, 1.1, 4)

#     # Draw rectangle around the faces
#     for (x, y, w, h) in faces:
#         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

        
#     # Display the output
#     face_im = im[y:y+h, x:x+w]
#     resized = cv2.resize(face_im, input_shape)
#     resized = np.reshape(resized, input_shape[0] * input_shape[1])
#     im_df = pd.DataFrame(resized)
#     #Resizing into 100x100 because we trained the model with this image size.
#     X = im_df / 255.0
#     X = X.values.reshape(-1,100,100,1)
#     #Calling the predict method on model to predict 'me' on the image
#     print(model.predict(X)[0][0])
#     prediction = model.predict(X)[0][0]
#     print(prediction)
# #    Closer prediction is to 1, stronger guess of NO MASK, closer is to 1, stronger guess of mask
#     if prediction < .6:
#         frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#         label = "No Mask"
#         cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
#     else:
#         label = "Mask"
#         cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

#     cv2.imshow("Capturing", frame)
#     key=cv2.waitKey(1)
#     if key == ord('q'):
#             break
# # video.release()
# # cv2.destroyAllWindows()

1/1 [==============================] - 0s 215ms/step
0.9247649
1/1 [==============================] - 0s 60ms/step
0.9247649
1/1 [==============================] - 0s 97ms/step
0.86731356
1/1 [==============================] - 0s 102ms/step
0.86731356
1/1 [==============================] - 0s 91ms/step
0.49608657
1/1 [==============================] - 0s 139ms/step
0.49608657
1/1 [==============================] - 0s 47ms/step
0.58475405
1/1 [==============================] - 0s 140ms/step
0.58475405
1/1 [==============================] - 0s 149ms/step
0.7332694
1/1 [==============================] - 0s 95ms/step
0.7332694
1/1 [==============================] - 0s 52ms/step
0.86308724
1/1 [==============================] - 0s 177ms/step
0.86308724
1/1 [==============================] - 0s 66ms/step
0.48467723
1/1 [==============================] - 0s 66ms/step
0.48467723
1/1 [==============================] - 0s 64ms/step
0.17857145
1/1 [==============================] - 0s 126ms/step


1/1 [==============================] - 0s 33ms/step
0.63705885
1/1 [==============================] - 0s 36ms/step
0.63705885
1/1 [==============================] - 0s 35ms/step
0.87480074
1/1 [==============================] - 0s 36ms/step
0.87480074
1/1 [==============================] - 0s 40ms/step
0.6383048
1/1 [==============================] - 0s 43ms/step
0.6383048
1/1 [==============================] - 0s 40ms/step
0.93845755
1/1 [==============================] - 0s 36ms/step
0.93845755
1/1 [==============================] - 0s 39ms/step
0.88150704
1/1 [==============================] - 0s 33ms/step
0.88150704
1/1 [==============================] - 0s 43ms/step
0.5345071
1/1 [==============================] - 0s 34ms/step
0.5345071
1/1 [==============================] - 0s 47ms/step
0.29939297
1/1 [==============================] - 0s 28ms/step
0.29939297
1/1 [==============================] - 0s 37ms/step
0.83770984
1/1 [==============================] - 0s 42ms/step
0.83770

1/1 [==============================] - 0s 43ms/step
0.8510286
1/1 [==============================] - 0s 28ms/step
0.8510286
1/1 [==============================] - 0s 33ms/step
0.81846666
1/1 [==============================] - 0s 35ms/step
0.81846666
1/1 [==============================] - 0s 35ms/step
0.78124917
1/1 [==============================] - 0s 35ms/step
0.78124917
1/1 [==============================] - 0s 27ms/step
0.6845639
1/1 [==============================] - 0s 31ms/step
0.6845639
1/1 [==============================] - 0s 28ms/step
0.7853845
1/1 [==============================] - 0s 36ms/step
0.7853845
1/1 [==============================] - 0s 30ms/step
0.93996567
1/1 [==============================] - 0s 33ms/step
0.93996567
1/1 [==============================] - 0s 28ms/step
0.8487174
1/1 [==============================] - 0s 35ms/step
0.8487174
1/1 [==============================] - 0s 33ms/step
0.94862616
1/1 [==============================] - 0s 28ms/step
0.94862616


1/1 [==============================] - 0s 38ms/step
0.8678674
1/1 [==============================] - 0s 40ms/step
0.8678674
1/1 [==============================] - 0s 35ms/step
0.89210093
1/1 [==============================] - 0s 40ms/step
0.89210093
1/1 [==============================] - 0s 31ms/step
0.82494575
1/1 [==============================] - 0s 38ms/step
0.82494575
1/1 [==============================] - 0s 30ms/step
0.9263126
1/1 [==============================] - 0s 36ms/step
0.9263126
1/1 [==============================] - 0s 35ms/step
0.94867456
1/1 [==============================] - 0s 35ms/step
0.94867456
1/1 [==============================] - 0s 29ms/step
0.92887753
1/1 [==============================] - 0s 60ms/step
0.92887753
1/1 [==============================] - 0s 33ms/step
0.9029686
1/1 [==============================] - 0s 31ms/step
0.9029686
1/1 [==============================] - 0s 36ms/step
0.90505534
1/1 [==============================] - 0s 42ms/step
0.9050553

In [6]:

# https://medium.com/@jinilcs/a-simple-keras-model-on-my-laptop-webcam-dda77521e6a0

# # Load the saved model
# # Define a function to make predictions
# input_shape = (100,100)
# def predict_mask(image):

#     frame = cv2.imread(image)
#     frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
#     face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
#     faces = face_cascade.detectMultiScale(frame, 1.1, 4)

#     for (x, y, w, h) in faces:
#         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

#     cv2.imshow('img', frame)
#     cv2.waitKey()
    
    
#     print(frame.shape)
#     image = cv2.resize(frame, input_shape)
#     image_array = np.array(image)
#     image_array = np.resize(image_array, (1, 100, 100))
    
#     image_array = image_array / 255.0
#     print(image_array.shape)
    
#     # Make a prediction with the model
#     prediction = model.predict(image_array)
#     print(prediction)
    
#     # Return the prediction
#     return prediction[0][0] > 0.5  # Returns True if wearing mask, False if not

# # Example usage
# # image = 'New_Masks_Dataset/Test/Mask/2085.jpg'
# # image = 'New_Masks_Dataset/Test/Non_Mask/real_01032.jpg'
# # image = 'New_Masks_Dataset/Test/Mask/2114.jpeg'
# # image = 'New_Masks_Dataset/Test/Non_Mask/real_01042.jpg'
# # image = 'mask.png'
# # image = 'no_mask.png'
# # image = 'opencv_frame_0.png'
# # image = 'opencv_frame_1.png'

# # image = "New_Masks_Dataset/Test/Non_Mask/real_01073.jpg"
# # folder = 'New_Masks_Dataset/Test/Non_Mask'
# # for image in os.listdir(folder):
# prediction = predict_mask(image)
# print(prediction)

(646, 970)
(1, 100, 100)
1/1 [==============================] - 0s 37ms/step
[[2.605992e-11 1.000000e+00]]
False


For the first model adding in the rotations and changes to the data set made the prediction DID NOT HAVE AN EFFECT on the accuracy of the data, I am going to be increasing the amount of transformations and see the effect it has

In [5]:
# model = load_model('best_model_3.h5')
# # Change to input_shape = (100,100,3) if using _2 2,3,5
# input_shape = (100,100)


In [3]:


# # Load the saved model
# # Define a function to make predictions
# input_shape = (100,100)

# def predict_mask(image):

#     frame = cv2.imread(image)
# #     frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#     image = cv2.resize(frame, input_shape)
#     # Convert the image to a numpy array
#     image_array = np.array(image)
    
#     # Resize the image to the correct dimensions (if necessary)
#     image_array = np.resize(image_array, (1, 100, 100,3))
    
#     # Normalize the image data
#     image_array = image_array / 255.0
#     print(image_array.shape)
    
#     # Make a prediction with the model
#     prediction = model.predict(image_array)
#     print(prediction)
    
#     # Return the prediction
#     return prediction[0][0] > 0.5  # Returns True if wearing mask, False if not

# # Example usage
# # image = 'New_Masks_Dataset/Test/Mask/2085.jpg'
# # image = 'New_Masks_Dataset/Test/Non_Mask/real_01032.jpg'
# # image = 'New_Masks_Dataset/Test/Mask/2114.jpeg'
# # image = 'New_Masks_Dataset/Test/Non_Mask/real_01042.jpg'
# image = 'mask.png' 
# # image = 'no_mask.png'
# # image = "New_Masks_Dataset/Test/Non_Mask/real_01073.jpg"
# # folder = 'New_Masks_Dataset/Test/Non_Mask'
# # for image in os.listdir(folder):
# prediction = predict_mask(image)
# print(prediction)

(1, 100, 100, 3)
1/1 [==============================] - 0s 271ms/step
[[0.9571363  0.04233744]]
True


In [1]:
import numpy as np
from tensorflow.keras.models import load_model
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd
import os

In [2]:
model = load_model('best_model_3.h5')
# Change to input_shape = (100,100,3) if using _2 2,3,5
input_shape = (100,100)


2023-05-09 13:51:59.103816: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# https://medium.com/@jinilcs/a-simple-keras-model-on-my-laptop-webcam-dda77521e6a0
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd

#Load the saved model
video = cv2.VideoCapture(0)
input_shape = (100,100)
video.set(10,100)

while True:
    _, frame = video.read()

    # frame = cv2.imread(filename)
    #Convert the captured frame into RGB
    im = frame
    
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_alt.xml')
#     haarcascade_frontalface_alt
#     haarcascade_frontalface_default
    faces = face_cascade.detectMultiScale(frame, 1.1, 4)
    if(len(faces) > 0):
    #     print(faces)
        # Draw rectangle around the faces
        face_im = im
        for (x, y, w, h) in faces:
            face_im = im[y:y+h + 20, x:x+w + 20]
        
        resized = cv2.resize(face_im, input_shape)
        # Convert the image to a numpy array
        image_array = np.array(resized)

        # Resize the image to the correct dimensions (if necessary)
        image_array = np.resize(image_array, (1, 100, 100,3))

        # Normalize the image data
        image_array = image_array / 255.0
        # Make a prediction with the model
        prediction = model.predict(image_array)
        print(prediction)
    #    Closer prediction is to 1, stronger guess of NO MASK, closer is to 1, stronger guess of mask
        pred = prediction[0][0] * 100

        if prediction[0][0] > .6:
            label = "No Mask"
            pred = prediction[0][0]*100
            for (x, y, w, h) in faces:
                cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 2)
                cv2.putText(frame, label + " " +str(pred), (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
        else:
            label = "Mask"
            pred = prediction[0][1]*100
            for (x, y, w, h) in faces:
                cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
                cv2.putText(frame, label +" "+ str(pred), (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    else:
        eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
        eyes = eye_cascade.detectMultiScale(frame, 1.1, 4,  minSize=(30, 30))
        face_im = im
        
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(frame, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
        

        resized = cv2.resize(face_im, input_shape)
        # Convert the image to a numpy array
        image_array = np.array(resized)


        # Resize the image to the correct dimensions (if necessary)
        image_array = np.resize(image_array, (1, 100, 100,3))

        # Normalize the image data
        image_array = image_array / 255.0
        # Make a prediction with the model
        prediction = model.predict(image_array)
        print(prediction)
    #    Closer prediction is to 1, stronger guess of NO MASK, closer is to 1, stronger guess of mask
        pred = prediction[0][0] * 100

        if prediction[0][0] > .6:
            label = "No Mask"
            pred = prediction[0][0]*100
            for (ex, ey, ew, eh) in eyes:
                cv2.rectangle(frame, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
                cv2.putText(frame, label + " " +str(pred), (ex, ey-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
        else:
            label = "Mask"
            pred = prediction[0][1]*100
            for (ex, ey, ew, eh) in eyes:
                cv2.rectangle(frame, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
                cv2.putText(frame, label + " " +str(pred), (ex, ey-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2)
    cv2.imshow("Capturing", frame)
    key=cv2.waitKey(1)
    if key == ord('q'):
            break
# video.release()
# cv2.destroyAllWindows()

1/1 [==============================] - 0s 194ms/step
[[0.591774  0.3931437]]
1/1 [==============================] - 0s 40ms/step
[[0.7762962  0.22490096]]
1/1 [==============================] - 0s 30ms/step
[[0.77069366 0.22954573]]
1/1 [==============================] - 0s 33ms/step
[[0.772679  0.2289034]]
1/1 [==============================] - 0s 35ms/step
[[0.77690244 0.22557664]]
1/1 [==============================] - 0s 39ms/step
[[0.78737766 0.214841  ]]
1/1 [==============================] - 0s 38ms/step
[[0.73796225 0.26768178]]
1/1 [==============================] - 0s 29ms/step
[[0.7154527  0.29445034]]
1/1 [==============================] - 0s 37ms/step
[[0.71799815 0.2913763 ]]
1/1 [==============================] - 0s 36ms/step
[[0.69418585 0.31580874]]
1/1 [==============================] - 0s 36ms/step
[[0.76510864 0.23851681]]
1/1 [==============================] - 0s 30ms/step
[[0.7740149  0.22835314]]
1/1 [==============================] - 0s 36ms/step
[[0.8084284  0.

1/1 [==============================] - 0s 135ms/step
[[0.63378066 0.37165675]]
1/1 [==============================] - 0s 90ms/step
[[0.7779318  0.22724956]]
1/1 [==============================] - 0s 103ms/step
[[0.618921  0.3931273]]
1/1 [==============================] - 0s 44ms/step
[[0.6335493 0.3736909]]
1/1 [==============================] - 0s 37ms/step
[[0.52936137 0.48150545]]
1/1 [==============================] - 0s 43ms/step
[[0.6231323  0.38638136]]
1/1 [==============================] - 0s 74ms/step
[[0.8134399  0.19061658]]
1/1 [==============================] - 0s 151ms/step
[[0.8206858  0.18407083]]
1/1 [==============================] - 0s 64ms/step
[[0.80439883 0.20291832]]
1/1 [==============================] - 0s 53ms/step
[[0.78372043 0.22197005]]
1/1 [==============================] - 0s 83ms/step
[[0.81275946 0.19306956]]
1/1 [==============================] - 0s 39ms/step
[[0.7991947 0.2073212]]
1/1 [==============================] - 0s 183ms/step
[[0.8117365  0

For the 2nd model which contained COLOR AND the rotations/changes to the data set. It made the accuracy in guessing between the two options A LOT WORSE

For the 3nd model which contained COLOR AND the rotations/changes, AND did not have a class_mode set to it, it made the false positve rate a lot higher, what this means is that most of the images are returning as true and even some of the stock photos which shouldn't have a high score are having a high score

For the 4nd model which contained did NOT contain COLOR AND but did have some transformations and the main thing about this is that it made in this one I worked to destory the training images, that ufortantely did not have as big of an effect as I would've liked to have and while it did make the values the test a lot higher it made the values for other images to be a lot worse.

For model 5 and 6, it DOES take in color, so the shape has to be in , the only difference that I made was that I added in more parameters to the model, and when checking the accuracy it seemed that it was more hyperfit and wasn't able to tell the difference as much

For model 7, I added 40 pictures (20 with masks and 20 without masks in different positions and locations) in both the train and test set (80 pictures in total) of me with my masks and wihout and then tested the accuracy then. The model was a lot better in detecting masks on me but I ultimately eneded up using 3 becaues of the fact that it didn't use my "cheat images"