In [3]:
import numpy as np
from tensorflow.keras.models import load_model
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd
import os

In [2]:
model = load_model('best_model_4.h5')
input_shape = (100,100)


2023-05-05 09:47:08.794002: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
# import cv2
# import tkinter as tk
# from PIL import Image, ImageTk

# class CameraApp:
#     def __init__(self, master):
#         self.master = master
#         master.title("Camera App")

#         # Create a button to take a picture
#         self.button = tk.Button(master, text="Take Picture", command=self.take_picture)
#         self.button.pack()

#         # Create a canvas to display the captured image
#         self.canvas = tk.Canvas(master, width=640, height=480)
#         self.canvas.pack()

#     def take_picture(self):
#         # Open the default camera
#         cap = cv2.VideoCapture(0)

#         # Capture a frame from the camera
#         ret, frame = cap.read()

#         # Save the captured frame as an image
#         self.image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY))

#         # Release the camera
#         cap.release()

#         # Display the captured image on the canvas
#         self.photo = ImageTk.PhotoImage(self.image)
#         self.canvas.create_image(0, 0, image=self.photo, anchor=tk.NW)

# root = tk.Tk()
# app = CameraApp(root)
# root.mainloop()

In [2]:
import cv2

cam = cv2.VideoCapture(0)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        img_name = "opencv_frame_{}.png".format(img_counter)
        cv2.imwrite(img_name, frame)
        print("{} written!".format(img_name))
        img_counter += 1

cam.release()

cv2.destroyAllWindows()

opencv_frame_0.png written!
opencv_frame_1.png written!
opencv_frame_2.png written!
opencv_frame_3.png written!
opencv_frame_4.png written!
opencv_frame_5.png written!
opencv_frame_6.png written!
opencv_frame_7.png written!
opencv_frame_8.png written!
opencv_frame_9.png written!
opencv_frame_10.png written!
opencv_frame_11.png written!
opencv_frame_12.png written!
opencv_frame_13.png written!
Escape hit, closing...


In [ ]:
# from flask import Flask

# app = Flask(__name__)

# @app.route("/")
# def hello_world():
#     return "<p>Hello, World!</p>"

In [ ]:
import cv2

img = cv2.imread(os.path.join('opencv_frame_0.png'))
grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
resized = cv2.resize(grayscale, input_shape)
resized = np.reshape(resized, input_shape[0] * input_shape[1])


# prediction = model.predict(image)
resized

In [3]:
# https://medium.com/@jinilcs/a-simple-keras-model-on-my-laptop-webcam-dda77521e6a0
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd

#Load the saved model
video = cv2.VideoCapture(0)
input_shape = (100,100)

while True:
    _, frame = video.read()

    # frame = cv2.imread(filename)
    #Convert the captured frame into RGB
    im = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(frame, 1.1, 4)

    # Draw rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

        
    # Display the output
    face_im = im[y:y+h, x:x+w]
    resized = cv2.resize(face_im, input_shape)
    resized = np.reshape(resized, input_shape[0] * input_shape[1])
    im_df = pd.DataFrame(resized)
    #Resizing into 100x100 because we trained the model with this image size.
    X = im_df / 255.0
    X = X.values.reshape(-1,100,100,1)
    #Calling the predict method on model to predict 'me' on the image
    print(model.predict(X)[0][0])
    prediction = model.predict(X)[0][0]
    print(prediction)
#    Closer prediction is to 1, stronger guess of NO MASK, closer is to 1, stronger guess of mask
    if prediction < .6:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        label = "No Mask"
        cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    else:
        label = "Mask"
        cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    cv2.imshow("Capturing", frame)
    key=cv2.waitKey(1)
    if key == ord('q'):
            break
# video.release()
# cv2.destroyAllWindows()

1/1 [==============================] - 0s 215ms/step
0.9247649
1/1 [==============================] - 0s 60ms/step
0.9247649
1/1 [==============================] - 0s 97ms/step
0.86731356
1/1 [==============================] - 0s 102ms/step
0.86731356
1/1 [==============================] - 0s 91ms/step
0.49608657
1/1 [==============================] - 0s 139ms/step
0.49608657
1/1 [==============================] - 0s 47ms/step
0.58475405
1/1 [==============================] - 0s 140ms/step
0.58475405
1/1 [==============================] - 0s 149ms/step
0.7332694
1/1 [==============================] - 0s 95ms/step
0.7332694
1/1 [==============================] - 0s 52ms/step
0.86308724
1/1 [==============================] - 0s 177ms/step
0.86308724
1/1 [==============================] - 0s 66ms/step
0.48467723
1/1 [==============================] - 0s 66ms/step
0.48467723
1/1 [==============================] - 0s 64ms/step
0.17857145
1/1 [==============================] - 0s 126ms/step


1/1 [==============================] - 0s 33ms/step
0.63705885
1/1 [==============================] - 0s 36ms/step
0.63705885
1/1 [==============================] - 0s 35ms/step
0.87480074
1/1 [==============================] - 0s 36ms/step
0.87480074
1/1 [==============================] - 0s 40ms/step
0.6383048
1/1 [==============================] - 0s 43ms/step
0.6383048
1/1 [==============================] - 0s 40ms/step
0.93845755
1/1 [==============================] - 0s 36ms/step
0.93845755
1/1 [==============================] - 0s 39ms/step
0.88150704
1/1 [==============================] - 0s 33ms/step
0.88150704
1/1 [==============================] - 0s 43ms/step
0.5345071
1/1 [==============================] - 0s 34ms/step
0.5345071
1/1 [==============================] - 0s 47ms/step
0.29939297
1/1 [==============================] - 0s 28ms/step
0.29939297
1/1 [==============================] - 0s 37ms/step
0.83770984
1/1 [==============================] - 0s 42ms/step
0.83770

1/1 [==============================] - 0s 43ms/step
0.8510286
1/1 [==============================] - 0s 28ms/step
0.8510286
1/1 [==============================] - 0s 33ms/step
0.81846666
1/1 [==============================] - 0s 35ms/step
0.81846666
1/1 [==============================] - 0s 35ms/step
0.78124917
1/1 [==============================] - 0s 35ms/step
0.78124917
1/1 [==============================] - 0s 27ms/step
0.6845639
1/1 [==============================] - 0s 31ms/step
0.6845639
1/1 [==============================] - 0s 28ms/step
0.7853845
1/1 [==============================] - 0s 36ms/step
0.7853845
1/1 [==============================] - 0s 30ms/step
0.93996567
1/1 [==============================] - 0s 33ms/step
0.93996567
1/1 [==============================] - 0s 28ms/step
0.8487174
1/1 [==============================] - 0s 35ms/step
0.8487174
1/1 [==============================] - 0s 33ms/step
0.94862616
1/1 [==============================] - 0s 28ms/step
0.94862616


1/1 [==============================] - 0s 38ms/step
0.8678674
1/1 [==============================] - 0s 40ms/step
0.8678674
1/1 [==============================] - 0s 35ms/step
0.89210093
1/1 [==============================] - 0s 40ms/step
0.89210093
1/1 [==============================] - 0s 31ms/step
0.82494575
1/1 [==============================] - 0s 38ms/step
0.82494575
1/1 [==============================] - 0s 30ms/step
0.9263126
1/1 [==============================] - 0s 36ms/step
0.9263126
1/1 [==============================] - 0s 35ms/step
0.94867456
1/1 [==============================] - 0s 35ms/step
0.94867456
1/1 [==============================] - 0s 29ms/step
0.92887753
1/1 [==============================] - 0s 60ms/step
0.92887753
1/1 [==============================] - 0s 33ms/step
0.9029686
1/1 [==============================] - 0s 31ms/step
0.9029686
1/1 [==============================] - 0s 36ms/step
0.90505534
1/1 [==============================] - 0s 42ms/step
0.9050553

In [6]:


# Load the saved model
# Define a function to make predictions
input_shape = (100,100)
def predict_mask(image):

    frame = cv2.imread(image)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(frame, 1.1, 4)

    # Draw rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Display the output
    cv2.imshow('img', frame)
    cv2.waitKey()
    
    
    print(frame.shape)
    image = cv2.resize(frame, input_shape)
    image_array = np.array(image)
    image_array = np.resize(image_array, (1, 100, 100))
    
    image_array = image_array / 255.0
    print(image_array.shape)
    
    # Make a prediction with the model
    prediction = model.predict(image_array)
    print(prediction)
    
    # Return the prediction
    return prediction[0][0] > 0.5  # Returns True if wearing mask, False if not

# Example usage
# image = 'New_Masks_Dataset/Test/Mask/2085.jpg'
# image = 'New_Masks_Dataset/Test/Non_Mask/real_01032.jpg'
# image = 'New_Masks_Dataset/Test/Mask/2114.jpeg'
# image = 'New_Masks_Dataset/Test/Non_Mask/real_01042.jpg'
# image = 'mask.png'
# image = 'no_mask.png'
# image = 'opencv_frame_0.png'
# image = 'opencv_frame_1.png'

# image = "New_Masks_Dataset/Test/Non_Mask/real_01073.jpg"
# folder = 'New_Masks_Dataset/Test/Non_Mask'
# for image in os.listdir(folder):
prediction = predict_mask(image)
print(prediction)

(646, 970)
(1, 100, 100)
1/1 [==============================] - 0s 37ms/step
[[2.605992e-11 1.000000e+00]]
False


For the first model adding in the rotations and changes to the data set made the prediction DID NOT HAVE AN EFFECT on the accuracy of the data, I am going to be increasing the amount of transformations and see the effect it has

In [5]:
model = load_model('best_model_3.h5')
# Change to input_shape = (100,100,3) if using _2 2,3,5
input_shape = (100,100)


In [3]:


# Load the saved model
# Define a function to make predictions
input_shape = (100,100)

def predict_mask(image):

    frame = cv2.imread(image)
#     frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    image = cv2.resize(frame, input_shape)
    # Convert the image to a numpy array
    image_array = np.array(image)
    
    # Resize the image to the correct dimensions (if necessary)
    image_array = np.resize(image_array, (1, 100, 100,3))
    
    # Normalize the image data
    image_array = image_array / 255.0
    print(image_array.shape)
    
    # Make a prediction with the model
    prediction = model.predict(image_array)
    print(prediction)
    
    # Return the prediction
    return prediction[0][0] > 0.5  # Returns True if wearing mask, False if not

# Example usage
# image = 'New_Masks_Dataset/Test/Mask/2085.jpg'
# image = 'New_Masks_Dataset/Test/Non_Mask/real_01032.jpg'
# image = 'New_Masks_Dataset/Test/Mask/2114.jpeg'
# image = 'New_Masks_Dataset/Test/Non_Mask/real_01042.jpg'
image = 'mask.png' 
# image = 'no_mask.png'
# image = "New_Masks_Dataset/Test/Non_Mask/real_01073.jpg"
# folder = 'New_Masks_Dataset/Test/Non_Mask'
# for image in os.listdir(folder):
prediction = predict_mask(image)
print(prediction)

(1, 100, 100, 3)
1/1 [==============================] - 0s 271ms/step
[[0.9571363  0.04233744]]
True


In [1]:
import numpy as np
from tensorflow.keras.models import load_model
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd
import os

In [2]:
model = load_model('best_model_3.h5')
# Change to input_shape = (100,100,3) if using _2 2,3,5
input_shape = (100,100)


2023-05-05 11:46:34.164646: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# https://medium.com/@jinilcs/a-simple-keras-model-on-my-laptop-webcam-dda77521e6a0
import cv2
import numpy as np
from PIL import Image
from keras import models
import pandas as pd

#Load the saved model
video = cv2.VideoCapture(0)
input_shape = (100,100)
video.set(10,100)

while True:
    _, frame = video.read()

    # frame = cv2.imread(filename)
    #Convert the captured frame into RGB
    im = frame
    
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(frame, 1.1, 4)
#     print(faces)
    # Draw rectangle around the faces
    face_im = im
    for (x, y, w, h) in faces:
        face_im = im[y:y+h, x:x+w]
    
    resized = cv2.resize(face_im, input_shape)
    # Convert the image to a numpy array
    image_array = np.array(resized)
    
    # Resize the image to the correct dimensions (if necessary)
    image_array = np.resize(image_array, (1, 100, 100,3))
    
    # Normalize the image data
    image_array = image_array / 255.0
    # Make a prediction with the model
    prediction = model.predict(image_array)
    print(prediction)
#    Closer prediction is to 1, stronger guess of NO MASK, closer is to 1, stronger guess of mask
    pred = prediction[0][0] * 100

    if prediction[0][0] > .6:
        label = "No Mask"
        pred = prediction[0][0]*100
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 2)
            cv2.putText(frame, label + " " +str(pred), (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
    else:
        label = "Mask"
        pred = prediction[0][1]*100
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.putText(frame, label +" "+ str(pred), (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    cv2.imshow("Capturing", frame)
    key=cv2.waitKey(1)
    if key == ord('q'):
            break
# video.release()
# cv2.destroyAllWindows()

[[471  91 352 352]]
1/1 [==============================] - 1s 766ms/step
[[0.7274765  0.28395122]]
[[468 103 352 352]]
1/1 [==============================] - 0s 61ms/step
[[0.7992945  0.21352924]]
[[465 100 352 352]
 [574 617  40  40]]
1/1 [==============================] - 0s 34ms/step
[[0.26806003 0.73345554]]
[[514 208 333 333]]
1/1 [==============================] - 0s 45ms/step
[[0.7744429  0.24076083]]
[[497 188 321 321]]
1/1 [==============================] - 0s 209ms/step
[[0.823274   0.19005653]]
[[434 117 417 417]]
1/1 [==============================] - 0s 65ms/step
[[0.86225325 0.14768705]]
[[489 318 364 364]]
1/1 [==============================] - 0s 38ms/step
[[0.8590151  0.15385072]]
[[475 265 419 419]]
1/1 [==============================] - 0s 31ms/step
[[0.8411103  0.16898379]]
[[487 273 440 440]]
1/1 [==============================] - 0s 37ms/step
[[0.89135814 0.11808728]]
[[500 197 501 501]]
1/1 [==============================] - 0s 61ms/step
[[0.84434223 0.1687483 ]]

1/1 [==============================] - 0s 36ms/step
[[0.2539373  0.74047387]]
[[480 249 302 302]
 [812 635  58  58]]
1/1 [==============================] - 0s 31ms/step
[[0.25913393 0.7344066 ]]
[[481 250 303 303]
 [811 634  60  60]]
1/1 [==============================] - 0s 33ms/step
[[0.23386885 0.7591687 ]]
[[471 247 318 318]
 [813 637  56  56]]
1/1 [==============================] - 0s 28ms/step
[[0.28824857 0.7035624 ]]
[[476 250 312 312]
 [814 636  58  58]]
1/1 [==============================] - 0s 28ms/step
[[0.24361904 0.7521444 ]]
[[477 244 314 314]]
1/1 [==============================] - 0s 35ms/step
[[0.70454514 0.3103263 ]]
[[479 254 302 302]
 [892 584  64  64]]
1/1 [==============================] - 0s 29ms/step
[[0.78760964 0.22177458]]
[[479 254 303 303]]
1/1 [==============================] - 0s 28ms/step
[[0.6818426  0.33249724]]
[[478 252 305 305]]
1/1 [==============================] - 0s 29ms/step
[[0.6789434  0.33835328]]
[[479 254 304 304]]
1/1 [==================

1/1 [==============================] - 0s 31ms/step
[[0.01406117 0.9868353 ]]
[[417 128 412 412]]
1/1 [==============================] - 0s 31ms/step
[[0.00207299 0.9979652 ]]
[[441 177 375 375]]
1/1 [==============================] - 0s 104ms/step
[[0.00990826 0.99045   ]]
[[662  93 567 567]
 [450 211 315 315]]
1/1 [==============================] - 0s 92ms/step
[[0.01160857 0.9887642 ]]
[[458 262 315 315]]
1/1 [==============================] - 0s 72ms/step
[[0.02847576 0.9719747 ]]
[[459 248 320 320]]
1/1 [==============================] - 0s 31ms/step
[[0.06564862 0.9330702 ]]
[[445 236 331 331]]
1/1 [==============================] - 0s 56ms/step
[[0.03035367 0.9697812 ]]
[[436 229 363 363]]
1/1 [==============================] - 0s 29ms/step
[[0.05859284 0.9402618 ]]
[[423 219 373 373]]
1/1 [==============================] - 0s 31ms/step
[[0.01519623 0.9855155 ]]
[[441 244 335 335]]
1/1 [==============================] - 0s 99ms/step
[[0.00414272 0.9962316 ]]
[[404 229 358 358]]


1/1 [==============================] - 0s 31ms/step
[[0.61204726 0.38477024]]
()
1/1 [==============================] - 0s 31ms/step
[[0.52645886 0.47499308]]
()
1/1 [==============================] - 0s 27ms/step
[[0.62403196 0.38748008]]
()
1/1 [==============================] - 0s 28ms/step
[[0.56464994 0.44093266]]
()
1/1 [==============================] - 0s 26ms/step
[[0.45612672 0.5591852 ]]
()
1/1 [==============================] - 0s 27ms/step
[[0.43509457 0.56975436]]
[[487 179 219 219]]
1/1 [==============================] - 0s 30ms/step
[[0.64964676 0.34685788]]
[[567 201 214 214]]
1/1 [==============================] - 0s 32ms/step
[[0.6439516  0.35420927]]
[[596 190 232 232]]
1/1 [==============================] - 0s 29ms/step
[[0.5995436  0.39647165]]
[[616 171 227 227]]
1/1 [==============================] - 0s 28ms/step
[[0.6122945  0.38641798]]
[[642 145 224 224]]
1/1 [==============================] - 0s 27ms/step
[[0.62223893 0.37357923]]
[[650 122 228 228]]
1/1 [==

1/1 [==============================] - 0s 42ms/step
[[0.6337319  0.37763292]]
()
1/1 [==============================] - 0s 32ms/step
[[0.8013201  0.20462348]]
()
1/1 [==============================] - 0s 33ms/step
[[0.5547434  0.44103974]]
()
1/1 [==============================] - 0s 35ms/step
[[0.7735641  0.23820485]]
()
1/1 [==============================] - 0s 26ms/step
[[0.81377554 0.19590934]]
()
1/1 [==============================] - 0s 31ms/step
[[0.7511229  0.25844893]]
()
1/1 [==============================] - 0s 29ms/step
[[0.87524915 0.13579397]]
()
1/1 [==============================] - 0s 27ms/step
[[0.574529   0.43692577]]
[[474 337  99  99]]
1/1 [==============================] - 0s 28ms/step
[[0.7641872  0.23854743]]
[[579  33 287 287]
 [528 304 104 104]]
1/1 [==============================] - 0s 29ms/step
[[0.80454165 0.19809023]]
[[670 275 125 125]
 [428 398  80  80]]
1/1 [==============================] - 0s 27ms/step
[[0.6567639  0.35405082]]
[[744 301 143 143]]
1/1

1/1 [==============================] - 0s 29ms/step
[[0.00753377 0.99293077]]
[[690 368 259 259]]
1/1 [==============================] - 0s 30ms/step
[[0.00401776 0.9961597 ]]
[[615 442 231 231]]
1/1 [==============================] - 0s 26ms/step
[[0.00801006 0.99263996]]
()
1/1 [==============================] - 0s 34ms/step
[[0.7754532  0.23378086]]
[[436 200  30  30]
 [495 198  52  52]]
1/1 [==============================] - 0s 29ms/step
[[0.01628755 0.9840296 ]]
[[593 526 188 188]]
1/1 [==============================] - 0s 27ms/step
[[0.02716541 0.9751931 ]]
[[480 124  59  59]
 [587 465 220 220]]
1/1 [==============================] - 0s 30ms/step
[[0.00611829 0.9943219 ]]
[[586 394 214 214]]
1/1 [==============================] - 0s 29ms/step
[[0.00525126 0.99511886]]
[[584 377 210 210]]
1/1 [==============================] - 0s 35ms/step
[[0.00462766 0.9956927 ]]
[[455  18  65  65]
 [589 365 212 212]]
1/1 [==============================] - 0s 35ms/step
[[0.00460679 0.99572533]]


[[0.03466635 0.96634364]]
[[452 169 345 345]]
1/1 [==============================] - 0s 30ms/step
[[0.02196812 0.9779347 ]]
[[503 219 330 330]]
1/1 [==============================] - 0s 30ms/step
[[0.04449299 0.9569798 ]]
[[487 199 319 319]]
1/1 [==============================] - 0s 29ms/step
[[0.03458347 0.966935  ]]
[[477 182 354 354]]
1/1 [==============================] - 0s 33ms/step
[[0.01851   0.9816442]]
[[497 194 324 324]]
1/1 [==============================] - 0s 29ms/step
[[0.03819092 0.9637992 ]]
[[524 127 379 379]]
1/1 [==============================] - 0s 30ms/step
[[0.005319   0.99513304]]
[[491  89 402 402]]
1/1 [==============================] - 23s 23s/step
[[0.00724284 0.993296  ]]
[[342  12 400 400]]
1/1 [==============================] - 0s 52ms/step
[[0.84479296 0.16810697]]
[[329  17 402 402]]
1/1 [==============================] - 0s 37ms/step
[[0.8551654  0.15822664]]
[[321  25 377 377]
 [411 344 172 172]
 [110 585  51  51]
 [650 628  49  49]]
1/1 [============

1/1 [==============================] - 0s 27ms/step
[[0.72240853 0.2867303 ]]
[[425 189 341 341]]
1/1 [==============================] - 0s 27ms/step
[[0.71886456 0.28943887]]
[[402 185 356 356]]
1/1 [==============================] - 0s 31ms/step
[[0.763087   0.24477497]]
[[409 191 348 348]]
1/1 [==============================] - 0s 35ms/step
[[0.7373698  0.27229124]]
[[403 193 352 352]]
1/1 [==============================] - 0s 33ms/step
[[0.75005895 0.2583202 ]]
[[421 205 329 329]]
1/1 [==============================] - 0s 38ms/step
[[0.7631233  0.24444549]]
[[424 202 335 335]]
1/1 [==============================] - 0s 29ms/step
[[0.764863   0.24377373]]
[[434 203 340 340]]
1/1 [==============================] - 0s 36ms/step
[[0.7257036 0.2826036]]
[[450 213 330 330]]
1/1 [==============================] - 0s 34ms/step
[[0.71207595 0.29905504]]
[[441 213 346 346]]
1/1 [==============================] - 0s 46ms/step
[[0.71296686 0.2937417 ]]
[[424 215 349 349]]
1/1 [=================

1/1 [==============================] - 0s 27ms/step
[[0.5168327 0.4856847]]
()
1/1 [==============================] - 0s 40ms/step
[[0.50345963 0.5019775 ]]
()
1/1 [==============================] - 0s 31ms/step
[[0.4825881  0.52413034]]
()
1/1 [==============================] - 0s 28ms/step
[[0.46784478 0.53870356]]
()
1/1 [==============================] - 0s 28ms/step
[[0.4649196 0.5425269]]
()
1/1 [==============================] - 0s 26ms/step
[[0.49339288 0.5076821 ]]
()
1/1 [==============================] - 0s 29ms/step
[[0.47591752 0.5277399 ]]
()
1/1 [==============================] - 0s 27ms/step
[[0.4069227  0.60190594]]
()
1/1 [==============================] - 0s 26ms/step
[[0.378962   0.62796205]]
()
1/1 [==============================] - 0s 26ms/step
[[0.33971548 0.66891456]]
()
1/1 [==============================] - 0s 31ms/step
[[0.2959755  0.71012956]]
()
1/1 [==============================] - 0s 26ms/step
[[0.69666755 0.3058135 ]]
()
1/1 [===========================

1/1 [==============================] - 0s 38ms/step
[[0.70980364 0.2991239 ]]
[[346  91 487 487]
 [513 316  83  83]]
1/1 [==============================] - 0s 35ms/step
[[0.68542933 0.32520315]]
[[506 318  88  88]]
1/1 [==============================] - 0s 33ms/step
[[0.7091391 0.3016512]]
()
1/1 [==============================] - 0s 33ms/step
[[0.9378351  0.06203113]]
()
1/1 [==============================] - 0s 26ms/step
[[0.9275618  0.07267152]]
()
1/1 [==============================] - 0s 26ms/step
[[0.9320419  0.06876957]]
()
1/1 [==============================] - 0s 27ms/step
[[0.9247702 0.0750204]]
[[531 304  83  83]
 [513 510 118 118]]
1/1 [==============================] - 0s 31ms/step
[[0.9700238  0.03256004]]
[[561 305  79  79]]
1/1 [==============================] - 0s 34ms/step
[[0.73716426 0.27378774]]
[[598 315  76  76]]
1/1 [==============================] - 0s 28ms/step
[[0.73885167 0.27208385]]
[[625 324  75  75]
 [785 382  61  61]]
1/1 [==============================

[[484 142 377 377]]
1/1 [==============================] - 0s 27ms/step
[[0.6168708 0.3940897]]
[[526 157 354 354]]
1/1 [==============================] - 0s 27ms/step
[[0.62689376 0.38354754]]
[[563 161 341 341]]
1/1 [==============================] - 0s 27ms/step
[[0.63975245 0.3663651 ]]
[[544 144 361 361]]
1/1 [==============================] - 0s 26ms/step
[[0.6487269  0.36253798]]
[[483 144 362 362]]
1/1 [==============================] - 0s 27ms/step
[[0.62795883 0.38631806]]
[[469 129 380 380]]
1/1 [==============================] - 0s 28ms/step
[[0.57849413 0.43654352]]
[[467 133 376 376]]
1/1 [==============================] - 0s 27ms/step
[[0.59304667 0.42334262]]
[[459 141 363 363]]
1/1 [==============================] - 0s 26ms/step
[[0.66908664 0.3508166 ]]
[[453 136 369 369]]
1/1 [==============================] - 0s 27ms/step
[[0.66371095 0.35213843]]
[[450 130 373 373]]
1/1 [==============================] - 0s 27ms/step
[[0.6678286  0.34892607]]
[[459 133 380 380]]
1/

For the 2nd model which contained COLOR AND the rotations/changes to the data set. It made the accuracy in guessing between the two options A LOT WORSE

For the 3nd model which contained COLOR AND the rotations/changes, AND did not have a class_mode set to it, it made the false positve rate a lot higher, what this means is that most of the images are returning as true and even some of the stock photos which shouldn't have a high score are having a high score

For the 4nd model which contained did NOT contain COLOR AND but did have some transformations and the main thing about this is that it made in this one I worked to destory the training images, that ufortantely did not have as big of an effect as I would've liked to have and while it did make the values the test a lot higher it made the values for other images to be a lot worse.